version: '2.1'
services:
  db:
    image: "postgres:11.3-alpine"
    restart: always
    volumes:
     - ./db/.pgdata:/var/lib/postgresql/data/

  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.3.0"
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - /usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
     - "8000:8000"
    depends_on:
     - db
     - elastic
